services:

  admin-backend:
    build:
      context: ./admin-transaction-back
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./admin-transaction-back:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - ./admin-transaction-back/.env.dev
    command: sh -c "npm install && npm run dev"
  
  admin-transaction-front:
    ports:
      - "3000:3000"
    env_file:
      - ./admin-transaction-front/.env.development
    volumes:
      - ./admin-transaction-front/src:/app/src
      - ./admin-transaction-front/public:/app/public
    stdin_open: true
